# Starter pipeline
trigger:
- master
- release/*

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Build the Excel file
      # ...

      # Publish the Excel file as an artifact
      Write-Host "##vso[artifact.upload artifacttype=file;artifactname=ExcelFile;]$(Build.SourcesDirectory)\ExcelFile.xlsx"

- task: SendEmail@1
  inputs:
    smtpServer: 'SMTP_Server'
    username: 'Username'
    password: 'Password'
    from: 'sender@example.com'
    to: 'recipient1@example.com,recipient2@example.com'
    subject: 'Build Success: Excel File Attached'
    body: |
      The build has succeeded. 
      The attached Excel file contains the latest data.
    attachments: '$(System.DefaultWorkingDirectory)/_ExcelFile/ExcelFile.xlsx'
  condition: succeeded()
